location            = "East US"
web_app_name        = "example-webapp-12345"
audit_tenant_id     = "your-audit-tenant-id"
main_client_id      = "your-main-client-id"
main_client_secret  = "your-main-client-secret"
main_tenant_id      = "your-main-tenant-id"
audit_client_id     = "your-audit-client-id"
audit_client_secret = "your-audit-client-secret"
