name: Setup Terraform Backend

on:
  push:
    paths:
      - 'base/backend/**'

jobs:
  terraform:
    name: Provision Backend Infra
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: base/backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.ARM_TENANT_ID }}"
            }

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="./base/backend/terraform.tfvars"


      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="./base/backend/terraform.tfvars"
