name: Terraform Plan and Apply Pipeline or workflow
on:
  push:
    branches:
      - main
    paths:
      - 'env/dev/app1-rg_demo/**'

jobs:
  terraform:
    name: Terraform RG Demo
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./env/dev/app1-rg_demo

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # IMPORTANT: The azure/login action primarily logs into Azure for the default context.
      # For this setup, we are explicitly passing all Service Principal credentials
      # via Terraform -var flags to ensure both default and aliased providers are configured.
      # You can keep this azure/login step as it provides a good initial login context.
      - name: Azure Login
        uses: azure/login@v1
        with:
          # Use your main SP credentials for the initial Azure login
          creds: |
            {
              "clientId": "${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.ARM_TENANT_ID }}"
            }

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        # Pass all Service Principal credentials as -var flags
        run: |
          terraform plan \
            -var-file="terraform.tfvars" \
            -var="main_client_id=${{ secrets.ARM_CLIENT_ID }}" \
            -var="main_client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
            -var="main_tenant_id=${{ secrets.ARM_TENANT_ID }}" 
      
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var-file="terraform.tfvars" \
            -var="main_client_id=${{ secrets.ARM_CLIENT_ID }}" \
            -var="main_client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
            -var="main_tenant_id=${{ secrets.ARM_TENANT_ID }}"
